//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LJV_DllSampleAll.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LJV_DLLSAMPLEALL_DIALOG     102
#define IDS_RESULT_LOG_FORMAT           102
#define IDD_SINGLEFUNCDLG               103
#define IDS_RESULT_OK                   103
#define IDS_RESULT_NG                   104
#define IDD_SETTINGDLG                  105
#define IDS_SCMD_INITIALIZE             105
#define IDS_SCMD_GETVERSION             106
#define IDS_SCMD_FINALIZE               107
#define IDS_SCMD_USBOPEN                108
#define IDS_SCMD_EHTERNETOPEN           109
#define IDS_SCMD_COMMCLOSE              110
#define IDS_SCMD_REBOOTCONTROLLER       111
#define IDS_SCMD_RETURNTOFACTORYSETTING 112
#define IDS_SCMD_GETERROR               113
#define IDS_SCMD_CLEARERROR             114
#define IDS_SCMD_TRIGGER                115
#define IDS_SCMD_STARTMEASURE           116
#define IDS_SCMD_STOPMEASURE            117
#define IDS_SCMD_AUTOZERO               118
#define IDS_SCMD_TIMING                 119
#define IDS_SCMD_RESET                  120
#define IDS_SCMD_CLEARMEMORY            121
#define IDS_SCMD_SETSETTING             122
#define IDS_SCMD_GETSETTING             123
#define IDS_SCMD_INITIALIZESETTING      124
#define IDS_SCMD_REFLECTSETTING         125
#define IDS_SCMD_REWRITETEMPORARYSETTING 126
#define IDS_SCMD_CHECKMEMORYACCESS      127
#define IDR_MAINFRAME                   128
#define IDS_SCMD_SETTIME                128
#define IDS_SCMD_GETTIME                129
#define IDS_SCMD_CHANGEACTIVEPROGRAM    130
#define IDS_SCMD_GETACTIVEPROGRAM       131
#define IDS_SCMD_GETMEASUREMENTVALUE    132
#define IDS_SCMD_GETPROFILE             133
#define IDS_SCMD_GETBATCHPROFILE        134
#define IDS_SCMD_GETPROFILEADVANCE      135
#define IDS_SCMD_GETBATCHPROFILEADVANCE 136
#define IDS_SCMD_STARTSTORAGE           137
#define IDS_SCMD_STOPSTORAGE            138
#define IDS_SCMD_GETSTORAGESTATUS       139
#define IDS_SCMD_GETSTORAGEDATA         140
#define IDS_SCMD_GETSTORAGEPROFILE      141
#define IDS_SCMD_GETSTORAGEBATCHPROFILE 142
#define IDS_SCMD_HIGHSPEEDDATAUSBCOMMUNICATIONINITALIZE 143
#define IDS_SCMD_HIGHSPEEDDATAETHERNETCOMMUNICATIONINITALIZE 144
#define IDS_SCMD_PRESTARTHIGHSPEEDDATACOMMUNICATION 145
#define IDS_SCMD_STARTHIGHSPEEDDATACOMMUNICATION 146
#define IDS_SCMD_STOPHIGHSPEEDDATACOMMUNICATION 147
#define IDS_SCMD_HIGHSPEEDDATACOMMUNICATIONFINALIZE 148
#define IDD_OPENETHERNETDLG             149
#define IDS_RC_FORMAT                   149
#define IDD_COMBINATIONFUNCDLG          150
#define IDS_RC_OK                       150
#define IDD_GETERRORDLG                 151
#define IDS_RC_ERR_OPEN_DEVICE          151
#define IDS_RC_ERR_NO_DEVICE            152
#define IDS_RC_ERR_SEND                 153
#define IDS_RC_ERR_RECEIVE              154
#define IDS_RC_ERR_TIMEOUT              155
#define IDD_CLEARERRORDLG               156
#define IDS_RC_ERR_PARAMETER            156
#define IDS_RC_ERR_NOMEMORY             157
#define IDD_OUTSELECTDLG                158
#define IDS_NOT_DEFINE_FORMAT           158
#define IDD_DEPTHPROGRAMSELECTDLG       159
#define IDD_TIMEDLG                     160
#define IDD_GETPROFILEDLG               162
#define IDD_GETBATCHPROFILEDLG          163
#define IDD_GETBATCHPROFILEADVANCEDLG   164
#define IDD_GETSTORAGESTATUSDLG         166
#define IDD_GETSTORAGEDATADLG           167
#define IDD_GETSTORAGEBATCHPROFILEDLG   168
#define IDD_HIGHSPEEDUSBINITIALIZEDLG   169
#define IDD_PRESTARTHIGHSPEEDDLG        172
#define IDD_HIGHSPEEDETHERNETINITIALIZEDLG 175
#define IDC_TAB                         1000
#define IDC_GB_COMLIB                   1001
#define IDC_BUTTON1                     1002
#define IDC_BTN_GETBATCHPROFILE         1002
#define IDC_BTN_GETVERSION              1002
#define IDC_BTN_COMMUNICATIONESTABLISHMENT 1002
#define IDC_BTN_GETBATCHPROFILE2        1003
#define IDC_BTN_INITIALIZE              1003
#define IDC_BTN_GETBATCHPROFILE3        1004
#define IDC_BTN_FINALIZE                1004
#define IDC_GB_COMLIB2                  1005
#define IDC_RADIO1                      1006
#define IDC_RADIO2                      1007
#define IDC_RD_STATE0                   1007
#define IDC_RD_ETHERNET                 1007
#define IDC_RADIO3                      1008
#define IDC_RD_STATE3                   1008
#define IDC_BTN_GETBATCHPROFILE8        1009
#define IDC_BTN_TRIGGER                 1009
#define IDC_BTN_GETBATCHPROFILE9        1010
#define IDC_BTN_ETHERNETOPEN            1010
#define IDC_BTN_GETBATCHPROFILE10       1011
#define IDC_BTN_COMMCLOSE               1011
#define IDC_BTN_GETBATCHPROFILE11       1012
#define IDC_BTN_USBOPEN                 1012
#define IDC_BTN_GETBATCHPROFILE12       1013
#define IDC_BTN_STARTMEASURE            1013
#define IDC_BTN_GETBATCHPROFILE13       1014
#define IDC_BTN_STOPMEASURE             1014
#define IDC_RADIO4                      1015
#define IDC_RD_STATE1                   1015
#define IDC_BTN_GETBATCHPROFILE15       1016
#define IDC_BTN_RESET                   1016
#define IDC_BTN_GETBATCHPROFILE16       1017
#define IDC_BTN_TIMING                  1017
#define IDC_BTN_GETBATCHPROFILE17       1018
#define IDC_BTN_CLEARMEMORY             1018
#define IDC_BTN_GETBATCHPROFILE47       1019
#define IDC_BTN_HIGHSPEEDDATAETHERNETCOMMUNICATIONINITALIZE 1019
#define IDC_BTN_GETBATCHPROFILE49       1020
#define IDC_BTN_STOPHIGHSPEEDDATACOMMUNICATION 1020
#define IDC_RADIO5                      1021
#define IDC_RD_STATE5                   1021
#define IDC_RADIO7                      1023
#define IDC_RD_STATE2                   1023
#define IDC_BUTTON2                     1024
#define IDC_SAVEMEASUREMENTVALUE        1024
#define IDC_BTN_COMMUNICATIONFINALIZATION 1024
#define IDC_BUTTON3                     1025
#define IDC_SAVE_PROFILE                1025
#define IDC_BTN_REFERENCEPROGRAMFILEPATH 1025
#define IDC_SPIN_PROFINDEX              1026
#define IDC_EDIT_PROFINDEX              1027
#define IDC_BTN_SAVE_DESTINATION        1028
#define IDC_BTN_GETBATCHPROFILE28       1029
#define IDC_BTN_GETPROFILE              1029
#define IDC_BTN_GETBATCHPROFILE29       1030
#define IDC_BTN_GETMEASUREMENTVALUE     1030
#define IDC_BTN_GETBATCHPROFILE30       1031
#define IDC_BTN_SETSETTIG               1031
#define IDC_BTN_GETBATCHPROFILE31       1032
#define IDC_BTN_PRESTARTHIGHSPEEDDATACOMMUNICATION 1032
#define IDC_EDIT_SAVEFILEPATH           1033
#define IDC_BTN_GETBATCHPROFILE37       1034
#define IDC_BTN_STARTSTORAGE            1034
#define IDC_BTN_GETBATCHPROFILE38       1035
#define IDC_BTN_GETSTORAGESTATUS        1035
#define IDC_BTN_GETBATCHPROFILE39       1036
#define IDC_BTN_STOPSTORAGE             1036
#define IDC_BTN_GETBATCHPROFILE33       1037
#define IDC_BTN_AUTOZERO                1037
#define IDC_BTN_GETBATCHPROFILE34       1038
#define IDC_BTN_GETBATCHPROFILEE        1038
#define IDC_CHK_TIMER                   1039
#define IDC_CHK_COUNTONLY               1040
#define IDC_BTN_GETBATCHPROFILE40       1041
#define IDC_BTN_GETSTORAGEDATA          1041
#define IDC_BTN_GETBATCHPROFILE41       1042
#define IDC_BTN_GETSTORAGEPROFILE       1042
#define IDC_BTN_GETBATCHPROFILE42       1043
#define IDC_BTN_GETSTORAGEBATCHPROFILE  1043
#define IDC_BTN_GETBATCHPROFILE48       1044
#define IDC_BTN_STARTHIGHSPEEDDATACOMMUNICATION 1044
#define IDC_BTN_GETBATCHPROFILE50       1045
#define IDC_BTN_HIGHSPEEDDATAUSBCOMMUNICATIONINITALIZE 1045
#define IDC_BTN_GETBATCHPROFILE53       1046
#define IDC_BTN_GETPROFILEADVANCE       1046
#define IDC_BTN_GETBATCHPROFILE54       1047
#define IDC_BTN_GETBATCHPROFILEADVANCE  1047
#define IDC_BTN_GETBATCHPROFILE18       1048
#define IDC_BTN_REFLECTSETTING          1048
#define IDC_BTN_GETBATCHPROFILE19       1049
#define IDC_BTN_GETSETTING              1049
#define IDC_BTN_GETBATCHPROFILE20       1050
#define IDC_BTN_INITIALIZESETTING       1050
#define IDC_SPIN_STARTTIMER             1051
#define IDC_BTN_GETBATCHPROFILE22       1052
#define IDC_BTN_REWRITETEMPORARYSETTING 1052
#define IDC_BTN_GETBATCHPROFILE23       1053
#define IDC_BTN_SETTIME                 1053
#define IDC_BTN_GETBATCHPROFILE24       1054
#define IDC_BTN_CHECKMEMORYACCESS       1054
#define IDC_BTN_GETBATCHPROFILE25       1055
#define IDC_BTN_GETTIME                 1055
#define IDC_BTN_GETBATCHPROFILE26       1056
#define IDC_BTN_CHANGEACTIVEPROGRAM     1056
#define IDC_BTN_GETBATCHPROFILE27       1057
#define IDC_BTN_GETACTIVEPROGRAM        1057
#define IDC_BTN_GETBATCHPROFILE43       1058
#define IDC_BTN_REBOOTCONTROLLER        1058
#define IDC_BTN_GETBATCHPROFILE44       1059
#define IDC_BTN_RETURNTOFACTORYSETTIG   1059
#define IDC_BTN_GETBATCHPROFILE45       1060
#define IDC_BTN_CLEARERROR              1060
#define IDC_BTN_GETBATCHPROFILE51       1061
#define IDC_BTN_HIGHSPEEDDATACOMMUNICATIONFINALIZE 1061
#define IDC_BTN_GETBATCHPROFILE52       1062
#define IDC_BTN_GETERROR                1062
#define IDC_EDIT_STARTTIMER             1063
#define IDC_CMB_COMP                    1065
#define IDC_CHK_ENVELOPE                1066
#define IDC_CMB_RANGE                   1067
#define IDC_CMB_BINNING                 1068
#define IDC_RD_ONEHEAD                  1071
#define IDC_RD_TWOHEAD                  1072
#define IDC_RD_TWOHEADWIDE              1073
#define IDC_COMMANDLOG                  1074
#define IDC_BTN_CLEARLOG                1075
#define IDC_RD_STATE4                   1078
#define IDC_STATIC_DEVICESTATUS1        1080
#define IDC_STATIC_DEVICESTATUS2        1081
#define IDC_STATIC_DEVICESTATUS3        1082
#define IDC_STATIC_DEVICESTATUS4        1083
#define IDC_STATIC_DEVICESTATUS5        1084
#define IDC_STATIC_DEVICESTATUS0        1085
#define IDC_STATIC_RECEIVE0             1086
#define IDC_STATIC_RECEIVE1             1087
#define IDC_STATIC_RECEIVE2             1088
#define IDC_STATIC_RECEIVE3             1089
#define IDC_STATIC_RECEIVE4             1090
#define IDC_STATIC_RECEIVE5             1091
#define IDC_IPADDRESS1                  1093
#define IDC_IPADDRESS                   1093
#define IDC_IPADDRESSCOMB               1093
#define IDC_PORTNUM                     1094
#define IDC_RD_USB                      1095
#define IDC_EDIT_COMMANDPORT            1096
#define IDC_EDIT_HIGHSPEEDPORT          1097
#define IDC_EDIT_PROGRAMFILEPATH        1098
#define IDC_BTN_UPLOADPROGRAM           1099
#define IDC_BTN_DOWNLOADPROGRAM         1100
#define IDC_CMB_SELECTPROGRAM           1101
#define IDC_BTN_GETCURRENTVALUE         1103
#define IDC_EDIT_MEASUREDATA            1107
#define IDC_EDIT_SAVEPATH               1108
#define IDC_BTN_REFERENCESAVEPATH       1109
#define IDC_BTN_GETPROFILEDATA          1110
#define IDC_BTN_GETBATCHPROFILEDATA     1111
#define IDC_BTN_GETPROFILEADVANCEDATA   1112
#define IDC_BTN_GETBATCHPROFILEDATAADVANCE 1113
#define IDC_BTN_BEGINHIGHSPEEDDATACOMMUNICATION 1114
#define IDC_EDIT_STARTPROFILENO         1116
#define IDC_EDIT_CALLBACKFREQUENCY      1117
#define IDC_EDIT_RECEIVEPROFILECOUNT    1118
#define IDC_BTN_TERMINATEHIGHSPEEDCOMMUNICATION 1119
#define IDC_EDIT_ERRCNT                 1121
#define IDC_EDIT_ERRORCODE              1126
#define IDC_EDIT1                       1127
#define IDC_EDIT_ONOFFREQ               1127
#define IDC_EDIT_YEAR                   1127
#define IDC_EDIT_TARGETBANK             1127
#define IDC_EDIT_READAREA               1127
#define IDC_CHECK1                      1144
#define IDC_CHECK2                      1145
#define IDC_CHECK3                      1146
#define IDC_CHECK4                      1147
#define IDC_CHECK5                      1148
#define IDC_CHECK6                      1149
#define IDC_CHECK7                      1150
#define IDC_CHECK8                      1151
#define IDC_CHECK9                      1152
#define IDC_CHECK10                     1153
#define IDC_CHECK11                     1154
#define IDC_CHECK12                     1155
#define IDC_CHECK13                     1156
#define IDC_CHECK14                     1157
#define IDC_CHECK15                     1158
#define IDC_CHECK16                     1159
#define IDC_STATIC_EXPLANATION          1160
#define IDC_STATIC_REQCOMMENT           1161
#define IDC_EDIT_TYPE                   1162
#define IDC_EDIT_CATEGORY               1163
#define IDC_EDIT_ITEM                   1164
#define IDC_EDIT_TARGET1                1165
#define IDC_EDIT_TARGET2                1166
#define IDC_EDIT_TARGET3                1168
#define IDC_EDIT_TARGET4                1169
#define IDC_EDIT_DEPTH                  1170
#define IDC_EDIT_DATAAMOUNT             1171
#define IDC_EDIT_PARAMETER              1174
#define IDC_STATIC_PARAMETERNOTE        1175
#define IDC_EDIT_TARGET                 1176
#define IDC_STATIC_HEX                  1177
#define IDC_STATIC_HEX2                 1177
#define IDC_STATIC_PROGRAMNOTE          1178
#define IDC_EDIT_SPECIFYNOTE            1179
#define IDC_STATIC_SPECIFYNOTE          1179
#define IDC_STATIC_SPECIFYNOTE2         1180
#define IDC_EDIT_MONTH                  1181
#define IDC_EDIT_DAY                    1182
#define IDC_EDIT_HOUR                   1183
#define IDC_EDIT_MINUTE                 1184
#define IDC_EDIT_SECOND                 1185
#define IDC_STATIC_LEVELNOTE            1186
#define IDC_STATIC_HEX1                 1187
#define IDC_STATIC_LEVEL                1188
#define IDC_EDIT5                       1192
#define IDC_EDIT_ERASEFLG               1192
#define IDC_EDIT_POSMODE                1193
#define IDC_EDIT_PROFILENO              1194
#define IDC_EDIT_PROFILECNT             1195
#define IDC_EDIT_BATCHNO                1197
#define IDC_EDIT_STARTNO                1203
#define IDC_EDIT_DATACNT                1204
#define IDC_EDIT_SURFACE                1206
#define IDC_EDIT_BATCHTOPPROFNO         1208
#define IDC_EDIT_PROFCNT                1209
#define IDC_STATIC_IPADDRESS_CAPTION    1217
#define IDC_STATIC_COMMANDPORT_CAPTION  1218
#define IDC_STATIC_HIGHSPEEDPORT_CAPTION 1219
#define IDC_EDIT_PROFCNT_BPA            1221

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1222
#define _APS_NEXT_SYMED_VALUE           176
#endif
#endif
